name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew -s check build
    - name: Check version
      run: ./ktcc_jvm -version
    - name: Integration tests
      run: ./ktcc_jvm_integration_test
